// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ibuHa0KrpmpjHa4DvGeYgn8jnQ9Gxog',
    appId: '1:698846391983:web:1ba1d8f2b10b3842bcee5a',
    messagingSenderId: '698846391983',
    projectId: 'todof3',
    authDomain: 'todof3.firebaseapp.com',
    storageBucket: 'todof3.appspot.com',
    measurementId: 'G-G8K11FWHB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGSSZwEJVRM1lZrrZljmEH8BppsyK5kY0',
    appId: '1:698846391983:android:d9976746e931f5c8bcee5a',
    messagingSenderId: '698846391983',
    projectId: 'todof3',
    storageBucket: 'todof3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZWzrcYs6D7140DKdDL9igswIvoiZcexc',
    appId: '1:698846391983:ios:9a5f18aef5abd7bdbcee5a',
    messagingSenderId: '698846391983',
    projectId: 'todof3',
    storageBucket: 'todof3.appspot.com',
    iosClientId: '698846391983-tdm1aarqsm2v90c83921tg7b8uoloffd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtTodoF3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZWzrcYs6D7140DKdDL9igswIvoiZcexc',
    appId: '1:698846391983:ios:9a5f18aef5abd7bdbcee5a',
    messagingSenderId: '698846391983',
    projectId: 'todof3',
    storageBucket: 'todof3.appspot.com',
    iosClientId: '698846391983-tdm1aarqsm2v90c83921tg7b8uoloffd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtTodoF3',
  );
}
